### ISSUE TITLE
[12.0] dump in performing "hr_timesheet_sheet"

### ISSUE THREAD

**Issue by ccandito** [OCA/timesheet#176]
Dear All,
in performing the timesheet the following short dump has occurred:
regards
claudio 

Uncaught TypeError: Cannot read property 'is' of undefined
http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:1563
Traceback:
TypeError: Cannot read property 'is' of undefined
    at Class._handleAttributes (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:1563:185)
    at Class._renderBodyCell (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3456:112)
    at Class.<anonymous> (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3450:374)
    at Function._.map._.collect (http://localhost:8069/web/content/719-8e0affc/web.assets_common.js:13:270)
    at Class._renderRow (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3450:252)
    at Function._.map._.collect (http://localhost:8069/web/content/719-8e0affc/web.assets_common.js:13:270)
    at Class._renderRows (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3450:46)
    at Class._renderBody (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3444:82)
    at Class._renderView (http://localhost:8069/web/content/865-fa12eb9/web.assets_backend.js:3443:247)
    at Class.prototype.(anonymous function) [as _renderView] (http://localhost:8069/web/content/719-8e0affc/web.assets_common.js:3537:488)

**Comment by pedrobaeza** [comment]
What is "performing the timesheet"? Please include detailed steps to reproduce the problem, and better in runbot.

**Comment by ccandito** [comment]
Dear All,
please find below the sequence of activities I performed:
timesheet --> create button
in the summary tab fill project and task fields
dump's occurred
after that, the screen is "locked" so it is not possible to go ahead
thanks in advance
claudio

**Comment by ccandito** [comment]
sorry, I've missed that:
timesheet --> create button
in the summary tab fill project and task fields
button add new line
dump's occurred
Regards
claudio

**Comment by astirpe** [comment]
@ccandito I just tried on Runbot. I cannot reproduce the problem.

**Comment by ccandito** [comment]
Ciao Andrea,
how can I help you?
regards
claudio

Il giorno gio 7 feb 2019 alle ore 09:13 Andrea Stirpe <
notifications@github.com> ha scritto:

**Comment by tarteo** [comment]
Maybe if you enable debug with assets mode (?debug=assets in the url) the error will be clearer. It can be unrelated to this module.
