### ISSUE TITLE
Overtime Request Failure in Odoo 12

### ISSUE THREAD

**Issue by Mtui** [OCA/timesheet#205]
Hello Folks,
Please assist with this issue in odoo 12 when trying to create new overtime request, it pops up this error.

Odoo Server Error
Traceback (most recent call last):
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\models.py", line 5351, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\models.py", line 5273, in _onchange_eval
    method_res = method(self)
  File "C:\Bitnami\odoo-12.0.20181018-1\apps\odoo\Lib\site-packages\odoo-12.0.post20181018-py3.7.egg\odoo\addons\hr_overtime_request\models\hr_overtime.py", line 33, in onchange_employee_id
    print("onchange_employee_idertcyubhijnok",onchange_employee_id)
NameError: name 'onchange_employee_id' is not defined

**Comment by pedrobaeza** [comment]
This is not an OCA module, so closing.
