### ISSUE TITLE
Odoo 10 refuse in 12

### ISSUE THREAD

**Issue by fco64** [OCA/timesheet#273]
Hi, 
first, sorry for my Elementary English.

I'm experiencing a problem in Odoo 12, the problem is in a call to method message_subscribe_users removed from 12.
so, I modifiede line 367 of  hr_timesheet_sheet/models/hr_timesheet_sheet.py as:

                # this is a refuse from Odoo 10
                # self.message_subscribe_users(
                #     user_ids=[sheet.employee_id.parent_id.user_id.id])
                self.message_subscribe(partner_ids=[sheet.employee_id.id])

But I'm not sure this is correct, please, could You verify and eventually correct?
Thanks
Franco

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem? Are you able to reproduce it on OCA runbot?

**Comment by fco64** [comment]
Hi,
no, I not tested with runbot.
To reproduce simply try to send to a Timesheet for approvation.

But, of course, if you search `message_subscribe_users` into entire Odoo folder You can't find it, also, the official documentation pages confirm the absence of method in new API.
Please check searching `message_subscribe_users`:
https://www.odoo.com/documentation/10.0/reference/mixins.html#basic-messaging-system
Vs.
https://www.odoo.com/documentation/10.0/reference/mixins.html#basic-messaging-system

Hope this is useful
Best regards
Ciao
Franco

**Comment by pedrobaeza** [comment]
But are you talking about using module for v10 in v12? That's not possible without code migration.

**Comment by fco64** [comment]
I'm using Odoo 12.0, for me is only a simple refuse of 10.0 in Your code.
Franco

**Comment by pedrobaeza** [comment]
I'm afraid I'm not understanding you

**Comment by rafaelbn** [comment]
@fco64 use runbot to test and be more clear please.

>  To reproduce simply try to send to a Timesheet for approvation.

![2019-09-01_1-17-22](https://user-images.githubusercontent.com/8736623/64069965-637e8300-cc56-11e9-8dcd-075d43bb8ae4.gif)

**Comment by ghost** [comment]
Hi All I am facing a similar issue. with odoo 12 and hr_timesheet_sheet addon . 
line number hr_timesheet_sheet.py", line 367
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_timesheet_sheet/models/hr_timesheet_sheet.py", line 367, in action_timesheet_confirm
    self.message_subscribe_users(
AttributeError: 'hr_timesheet.sheet' object has no attribute 'message_subscribe_users'`

**Comment by franciscoitligthen** [comment]
I'm having the same issue while running at Odoo 12. Does anyone know the solution for this problem?
