### ISSUE TITLE
Error installing module hr_timesheet_task_stag

### ISSUE THREAD

**Issue by cfdiaz** [OCA/timesheet#282]
Error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/var/lib/default-addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-171>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/var/lib/default-addons/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/var/lib/default-addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/var/lib/default-addons/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view account.analytic.line.tree definition in hr_timesheet_task_stage/views/account_analytic_line.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/var/lib/default-addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/lib/default-addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/var/lib/default-addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/var/lib/default-addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/var/lib/default-addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/var/lib/default-addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-171>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/var/lib/default-addons/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _model_create_multi
    return create(self, [arg])
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/var/lib/default-addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/var/lib/default-addons/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/var/lib/default-addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view account.analytic.line.tree definition in hr_timesheet_task_stage/views/account_analytic_line.xml
None" while parsing /var/lib/extra-addons/hr_timesheet_task_stage/views/account_analytic_line.xml:8, near
<record id="account_analytic_line_tree" model="ir.ui.view">
        <field name="name">account.analytic.line.tree</field>
        <field name="model">account.analytic.line</field>
        <field name="inherit_id" ref="hr_timesheet.hr_timesheet_line_tree"/>
        <field name="arch" type="xml">
            <field name="task_id" position="after">
                <field name="is_task_closed" invisible="1"/>
                <button name="action_close_task" string="Close task" tabindex="-1" type="object" icon="fa-folder-o" attrs="{'invisible': ['|', ('is_task_closed', '=', True), ('task_id', '=', False)]}"/>
                <button name="action_open_task" string="Open task" tabindex="-1" type="object" icon="fa-folder-open-o" attrs="{'invisible': ['|', ('is_task_closed', '=', False), ('task_id', '=', False)]}"/>
            </field>
        </field>
    </record>
```

**Comment by pedrobaeza** [comment]
I have that module working in my instance and it's working as well on runbot...

**Comment by pedrobaeza** [comment]
Odoo version by the way?

**Comment by pedrobaeza** [comment]
Do you have your Odoo source updated?

**Comment by cfdiaz** [comment]
Yes, i have odoo source updated, You could check the error message, what do you think it could be?

On Nov. 4, 2019 3:41 a.m., "Pedro M. Baeza" <notifications@github.com> wrote:

Do you have your Odoo source updated?

**Comment by pedrobaeza** [comment]
I don't see anything wrong. Please try in a fresh installation.

**Comment by cfdiaz** [comment]
This is a fresh installation, the error is related to an analytical account

On Nov. 4, 2019 5:39 a.m., "Pedro M. Baeza" <notifications@github.com> wrote:

I don't see anything wrong. Please try in a fresh installation.

**Comment by pedrobaeza** [comment]
Well, the module is installed without problems as you can see in https://runbot.odoo-community.org/runbot/117/12.0, so it seems an incompatible module or outdated code. Any way, closing meanwhile there's no more evidences of something wrong in this side.
