### ISSUE TITLE
crm_timesheet: issue with tests

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#331]
Around midnight UTC:
```
2020-02-18 23:22:06,571 5936 INFO openerp_test odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
----------
FAIL
FAIL
FAIL
FAIL: test_aal_time_control_flow (odoo.addons.project_timesheet_time_control.tests.test_project_timesheet_time_control.TestProjectTimesheetTimeControl)
` Test account.analytic.line time controls.
Traceback (most recent call last):
`   File "/home/travis/dependencies/project/project_timesheet_time_control/tests/test_project_timesheet_time_control.py", line 94, in test_aal_time_control_flow
`     self.assertLessEqual(wizard.date, date.today())
` AssertionError: datetime.date(2020, 2, 19) not less than or equal to datetime.date(2020, 2, 18)
FAIL: test_project_time_control_flow (odoo.addons.project_timesheet_time_control.tests.test_project_timesheet_time_control.TestProjectTimesheetTimeControl)
` Test project.project time controls.
Traceback (most recent call last):
`   File "/home/travis/dependencies/project/project_timesheet_time_control/tests/test_project_timesheet_time_control.py", line 161, in test_project_time_control_flow
`     self.assertLessEqual(wizard.date, date.today())
` AssertionError: datetime.date(2020, 2, 19) not less than or equal to datetime.date(2020, 2, 18)
FAIL: test_task_time_control_flow (odoo.addons.project_timesheet_time_control.tests.test_project_timesheet_time_control.TestProjectTimesheetTimeControl)
` Test project.task time controls.
Traceback (most recent call last):
`   File "/home/travis/dependencies/project/project_timesheet_time_control/tests/test_project_timesheet_time_control.py", line 195, in test_task_time_control_flow
`     self.assertLessEqual(wizard.date, date.today())
` AssertionError: datetime.date(2020, 2, 19) not less than or equal to datetime.date(2020, 2, 18)
FAILED
Module project_timesheet_time_control: 3 failures, 0 errors
FAIL
FAIL: test_lead_time_control_flow (odoo.addons.crm_timesheet.tests.test_account_analytic_line.AccountAnalyticLineCase)
` Test crm.lead time controls.
Traceback (most recent call last):
`   File "/home/travis/build/OCA/timesheet/crm_timesheet/tests/test_account_analytic_line.py", line 87, in test_lead_time_control_flow
`     self.assertLessEqual(wizard.date, date.today())
` AssertionError: datetime.date(2020, 2, 19) not less than or equal to datetime.date(2020, 2, 18)
FAILED
```

**Comment by alexey-pelykh** [comment]
cc @pedrobaeza `project_timesheet_time_control` is present as well with issue around midnight

**Comment by pedrobaeza** [comment]
Yeah, I know. Don't work at that hours. It's not healthy :stuck_out_tongue_closed_eyes: 

I haven't checked how to avoid that problem.

**Comment by alexey-pelykh** [comment]
Clearly, it's the timezone issue that something is wrong either in code or in tests, since default test user in runbot is in Brussels timezone or something like that.

**Comment by pedrobaeza** [comment]
Yeah, I suppose fixing time references and using some mock on them will avoid this problem.
