### ISSUE TITLE
Error on pressing "start working"

### ISSUE THREAD

**Issue by faithiology** [OCA/timesheet#464]
I must be missing something or it is a bug?
I created a new project, then a new task then pressed to "start working" so it starts counting the time consumed in working on this task.
![Screen Shot 2021-10-13 at 11 42 01 PM](https://user-images.githubusercontent.com/818427/137216840-91302061-e095-4853-8e88-5825ee0fa9ed.png)
as the above pic shows.
then it raises an error.
![Screen Shot 2021-10-13 at 11 42 21 PM](https://user-images.githubusercontent.com/818427/137216954-2bd34cb7-99aa-4ced-9e38-b5c2fa1a4b9e.png)
I will also list the error below.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14ce/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14ce/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14ce/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14ce/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14ce/custom/addons/project_timesheet_time_control/wizards/hr_timesheet_switch.py", line 143, in action_switch
    self.read(_fields)
  File "/opt/odoo14ce/custom/addons/sale_timesheet_rounded/models/account_analytic_line.py", line 97, in read
    fields_local = fields.copy() if fields else []
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14ce/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'odict_keys' object has no attribute 'copy'

**Comment by pedrobaeza** [comment]
It seems an incompatibility with the module sale_timesheet_rounded

**Comment by faithiology** [comment]
Will uninstall it and feed you back.

Edit:
Thank you so much @pedrobaeza 
I uninstalled it and it worked nicely so far.. if any other incompatibility appeared I will report

**Comment by bosd** [comment]
Encountering the same problem.
Would be nice to have both modules available as they could complement each other.

This issue is mentioned before. https://github.com/OCA/timesheet/pull/363
Looks like the fix is not forward ported.
